import bcrypt from "bcryptjs";
export const data = {
  Users: [
    {
      name: "Abhishek Parmar",
      email: "abhishek@king.com",
      password: bcrypt.hashSync("abhishek"),
      isAdmin: true,
    },
    {
      name: "Abhishek Singh",
      email: "abhishek@user.com",
      password: bcrypt.hashSync("abhishek"),
      isAdmin: false,
    },
  ],
  Product: [
    {
      _id: "1",
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      banner: "/images/shirt1.jpg",
    },
    {
      _id: "2",
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 3.2,
      numReview: 10,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      banner: "/images/banner2.jpg",
    },
    {
      _id: "3",
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReview: 3,
      countInStock: 20,
      description: "A popular shirt",
      banner: "/images/banner2.jpg",
    },
    {
      _id: "4",
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "Oliver",
      rating: 2.9,
      numReview: 13,
      countInStock: 20,
      description: "Smart looking pants",
      banner: "/images/banner2.jpg",
    },
    {
      _id: "5",
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 95,
      brand: "Zara",
      rating: 3.5,
      numReview: 7,
      countInStock: 20,
      description: "A popular pants",
      banner: "/images/banner2.jpg",
    },
    {
      _id: "6",
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 75,
      brand: "Casely",
      rating: 2.4,
      numReview: 14,
      countInStock: 20,
      description: "A popular pants",
      banner: "/images/banner2.jpg",
    },
  ],
};
